basePath: /
definitions:
  inmemory.Request:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  record.Request:
    properties:
      endDate:
        type: string
      maxCount:
        type: integer
      minCount:
        type: integer
      startDate:
        type: string
    type: object
  record.Response:
    properties:
      code:
        type: integer
      msg:
        type: string
      records: {}
    type: object
info:
  contact:
    email: aleynaguzel2109@gmail.com
    name: '#aleyna'
  description: An application with Swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  version: "1.0"
paths:
  /in-memory:
    get:
      consumes:
      - application/json
      description: Get func fetch data from an in-memory database.
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: notfound
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: gets value of key
      tags:
      - Memory
  /in-memory/:
    post:
      consumes:
      - application/json
      description: set data to an in-memory .
      parameters:
      - description: InmemoryRequest
        in: body
        name: inmemoryRequest
        required: true
        schema:
          $ref: '#/definitions/inmemory.Request'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: notfound
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: set data to an in-memory .
      tags:
      - Memory
  /records:
    post:
      consumes:
      - application/json
      description: func fetch data from records collection.
      parameters:
      - description: RecordRequest
        in: body
        name: recordRequest
        required: true
        schema:
          $ref: '#/definitions/record.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/record.Response'
            type: array
        "400":
          description: error
          schema:
            type: string
        "404":
          description: notfound
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: func fetch data from records collection.
      tags:
      - Record
swagger: "2.0"
